---

- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-ovirt_vm_create.git
  version: origin/master
  name: ovirt_vm_create
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-update_packages.git
  version: origin/master
  name: update_packages
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-selinux.git
  version: origin/master
  name: selinux
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-mongodb.git
  version: origin/master
  name: mongodb
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-graylog.git
  version: origin/master
  name: graylog
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-nginx.git
  version: origin/master
  name: nginx
- src: git+http://gitlab.ekaterinburg.fsin.uis/ansible/ansible-role-firewall.git
  version: origin/master
  name: firewall
